name: WebOS update

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of every month
  workflow_dispatch: # Allows manual triggering

jobs:
  check_url:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Make a request to the URL
        id: url_check
        run: |
          RESPONSE=$(curl -s "$URL_SECRET")
          echo "Response: $RESPONSE"
          RESULT=$(echo "$RESPONSE" | jq -r '.result')
          ERROR_CODE=$(echo "$RESPONSE" | jq -r '.errorCode')
          ERROR_MSG=$(echo "$RESPONSE" | jq -r '.errorMsg')

          echo "RESULT=$RESULT" >> $GITHUB_ENV
          echo "ERROR_CODE=$ERROR_CODE" >> $GITHUB_ENV
          echo "ERROR_MSG=$ERROR_MSG" >> $GITHUB_ENV

          if [ "$RESULT" != "success" ]; then
            echo "success=false" >> $GITHUB_ENV
          else
            echo "success=true" >> $GITHUB_ENV
          fi
        env:
          URL_SECRET: ${{ secrets.REQUEST_URL }}

      - name: Fail if the request did not succeed
        if: env.success == 'false'
        run: |
          echo "Request failed with error code: ${{ env.ERROR_CODE }} and message: ${{ env.ERROR_MSG }}"

      - name: Send email on failure
        if: env.success == 'false'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER_ADDRESS }}
          server_port: ${{ secrets.MAIL_SERVER_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: ${{ secrets.MAIL_TO }}
          from: Confido Check # <user@example.com>
          subject: URL Check Failed
          body: |
            The URL ${{ secrets.REQUEST_URL }} returned result: "${{ env.RESULT }}"
            Error code: ${{ env.ERROR_CODE }}
            Error message: ${{ env.ERROR_MSG }}

      - name: Notify success
        if: env.success == 'true'
        run: echo "Request was successful."
