name: WebOS update

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of every month
  workflow_dispatch: # Allows manual triggering

jobs:
  check_url:
    runs-on: ubuntu-latest

    steps:
      - name: Make a request to the URL
        id: url_check
        run: |
          RESPONSE=$(curl -s "$URL_SECRET")
          echo "Response: $RESPONSE"
          RESULT=$(echo "$RESPONSE" | jq -r '.result')
          if [ "$RESULT" != "success" ]; then
            exit 1
          fi
        env:
          URL_SECRET: ${{ secrets.REQUEST_URL }}

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER_ADDRESS }}
          server_port: ${{ secrets.MAIL_SERVER_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: ${{ secrets.MAIL_TO }}
          from: WebOS Check # <user@example.com>
          subject: WebOS dev mode extension failed
          body: |
            The URL ${{ secrets.REQUEST_URL }} returned response: $RESPONSE
